### ISSUE TITLE
Whoever can compile the latest 1.14 tensorrt and send me the latest 28b, I'll test it

### ISSUE THREAD

**Issue by awsjgy** [lightvector/KataGo#876] opened 2023-12-31 16:21 UTC

**Comment by awsjgy** [comment] 2023-12-31 16:28
I found this 28b in https://drive.google.com/drive/folders/1p_netnlWcy8K7YoFmKckOeBFRUmokuIp.but it's not the latest.,It's December 10th.,There's definitely a stronger one now.,Can you give me a download address.

**Comment by lightvector** [comment] 2023-12-31 18:16
That's the most recent one. The new network will take months to catch up to and surpass the existing nets, so please be patient, there's no point taking extremely frequent snapshots. I'll release another snapshot at some point.

**Comment by lightvector** [comment] 2023-12-31 18:22
I'm closing this issue, as it's also more or less a duplicate of the other issue already opened. You can continue to post there, thanks!

**Closed by lightvector** 2023-12-31 18:22 UTC
