### ISSUE TITLE
train.sh just quits with no explanation

### ISSUE THREAD

**Issue by iopq** [lightvector/KataGo#85] opened 2019-11-27 05:44 UTC
first it looks like it's working:

```
INFO:tensorflow:loss = 3.2412126, step = 265210
INFO:tensorflow:bbcdfloss = 0.0, bbpdfloss = 0.0, nsamp = 67893504, oloss = 0.3691904, p0loss = 0.8435641, p1loss = 0.13824266, pacc1 = 0.8611961, pslr = 6e-05, ptentr = 0.6576263, rloss = 0.152081, roloss = 0.00575159, rscloss = 0.00036645946, rsdloss = 9.392263e-05, rsmloss = 9.348117e-05, rwlloss = 0.014870121, sbcdfloss = 0.07569121, sbpdfloss = 0.042829152, smloss = 0.0, uvloss = 0.002928842, ventr = 0.37455636, vloss = 0.56091243, wsum = 0.0
```

but then it just quits

```
real	10m28.423s
user	64m0.033s
sys	0m52.680s
```

I haven't progressed past the first step, it quits right there

**Comment by iopq** [comment] 2019-11-27 05:50
Logs say:

```
2019-11-27 13:37:42.738057: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcudart.so.10.0'; dlerror: libcudart.so.10.0: cannot open shared object file: No such file or directory
2019-11-27 13:37:42.738111: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcublas.so.10.0'; dlerror: libcublas.so.10.0: cannot open shared object file: No such file or directory
2019-11-27 13:37:42.738160: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcufft.so.10.0'; dlerror: libcufft.so.10.0: cannot open shared object file: No such file or directory
2019-11-27 13:37:42.738208: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcurand.so.10.0'; dlerror: libcurand.so.10.0: cannot open shared object file: No such file or directory
2019-11-27 13:37:42.738257: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcusolver.so.10.0'; dlerror: libcusolver.so.10.0: cannot open shared object file: No such file or directory
2019-11-27 13:37:42.738306: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcusparse.so.10.0'; dlerror: libcusparse.so.10.0: cannot open shared object file: No such file or directory
```

my libraries are actually newer than this

**Comment by Friday9i** [comment] 2019-11-28 15:43
Which OS?
For windows 10 (last version), I use successfully:
- python 3.7.4
- tensorflow-GPU 1.15.0
- cuda 10 & 10.1, and associated Cudnn files
- nvidia driver from september (336.48 iirc): warning, with october and november version, I had random freezes during training (either at start or somewhere in the middle of the steps), and I almost went mad to identify the cause (I thought I had upgraded to october's version and it was ok, so when I upgraded to november's version and it began to crash, I tested back with october's version, and it was crashing, so I thought it was not the cause ; -(((. Anyway, it IS the cause).
- latest SDK

**Comment by iopq** [comment] 2019-11-28 18:23
I have the wrong CUDA version, too new to use with Tensorflow. How do I install the older version? It's being really annoying and trying to install versions of things that are too new

**Comment by lightvector** [comment] 2019-12-17 04:18
Given that you've been commenting about various training-related things, I'm going to consider this handled and close it. Please comment back if you think there's something to fix here.

**Closed by lightvector** 2019-12-17 04:18 UTC
