### ISSUE TITLE
Compiling the cuda version on Archlinux current

### ISSUE THREAD

**Issue by Pasteldenata** [lightvector/KataGo#178] opened 2020-03-28 02:34 UTC
All files compile, but I get linker errors: 
--------------
[ 100%] Linking CXX executable katago
/usr/bin/ld: CMakeFiles/katago.dir/program/play.cpp.o: in function `failIllegalMove(Search*, Logger&, Board, short)':
/home/gus/Arch/KataGo/cpp/program/play.cpp:659: undefined reference to `std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >::basic_ostringstream()'
--------------

...and so on.

**Comment by lightvector** [comment] 2020-03-28 14:24
Can you compile any basic C++ programs at all? ostringstream and things like that are just the standard C++ library, so this may be some configuration issue with your system or your C++ compiler.

When I Google for it I get some results that suggest that this can be caused by version mismatches between what compiler version you used for different files or libraries, or maybe between your linker or std library files. Have you tried investigating things like this? Does it happen on a full clean rebuild?

**Comment by Pasteldenata** [comment] 2020-03-28 20:11
Yes, in fact I can compile and link the opencl version of katago, the issue appears only in the cuda version.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by lightvector** [comment] 2020-03-28 20:57
Ah, so that means you should check out this table:
https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html

This is for CUDA 10.2. If you have an older version than that, then presumably the table is again different.

**Comment by Pasteldenata** [comment] 2020-03-29 01:42
Thank you, I understand now. Versions of gcc above 8 are not supported...

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by lightvector** [comment] 2020-04-18 00:14
Let me know if you have any further questions or if there's anything else to do here! Closing for now.

**Closed by lightvector** 2020-04-18 00:14 UTC
