### ISSUE TITLE
New release for CUDNN 8, CUDA11?

### ISSUE THREAD

**Issue by formosa-james** [lightvector/KataGo#282] opened 2020-07-28 01:17 UTC
Since CUDNN 8.02 is officially released, would lightvector release a version for CUDNN 8? It would be beneficial for new coming Ampere GPU.

**Comment by egri-nagy** [comment] 2020-08-11 01:00
I tried to compile KataGo on Ubuntu 20.04 with CUDA11 and CUDNN 8.0.239-1. Predictably, the compilation fails when it gets to the backend.

```
[ 42%] Building CXX object CMakeFiles/katago.dir/neuralnet/cudabackend.cpp.o
In file included from KataGo/cpp/neuralnet/cudabackend.cpp:2:
KataGo/cpp/neuralnet/cudabackend.cpp: In constructor ‘ConvLayer::ConvLayer(CudaHandles*, const ConvLayerDesc*, int, cudnnTensorStruct* const*, cudnnTensorStruct* const*, bool, bool)’:
KataGo/cpp/neuralnet/cudabackend.cpp:266:11: error: ‘CUDNN_CONVOLUTION_FWD_PREFER_FASTEST’ was not declared in this scope; did you mean ‘CUDNN_CONVOLUTION_BWD_FILTER_ALGO_3’?
  266 |           CUDNN_CONVOLUTION_FWD_PREFER_FASTEST,
      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
KataGo/cpp/neuralnet/../neuralnet/cudaerrorcheck.h:46:48: note: in definition of macro ‘CUDNN_ERR’
   46 | #define CUDNN_ERR(opName,x) { checkCudnnError((x),opName,__FILE__,#x,__LINE__); }
      |                                                ^
KataGo/cpp/neuralnet/cudabackend.cpp:260:32: error: ‘cudnnGetConvolutionForwardAlgorithm’ was not declared in this scope; did you mean ‘cudnnGetConvolutionForwardAlgorithm_v7’?
  260 |         CUDNN_ERR(name.c_str(),cudnnGetConvolutionForwardAlgorithm(
      |                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
KataGo/cpp/neuralnet/../neuralnet/cudaerrorcheck.h:46:48: note: in definition of macro ‘CUDNN_ERR’
   46 | #define CUDNN_ERR(opName,x) { checkCudnnError((x),opName,__FILE__,#x,__LINE__); }
      |                                                ^
make[2]: *** [CMakeFiles/katago.dir/build.make:460: CMakeFiles/katago.dir/neuralnet/cudabackend.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:76: CMakeFiles/katago.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
```

**Comment by apetresc** [comment] 2020-08-14 01:28
This is a duplicate of #244, I believe.

**Comment by lightvector** [comment] 2020-11-09 15:16
Version 1.7.0 is released, with precompiled exes for CUDA 11.1.

If the versions of shared libraries and other things don't work out for you (as might be the case for some users, particularly on alternate versions of LInux), then of course you can also build from source. Unlike windows, this often is pretty straightforward, and should in fact be a bit easier too now with boost no longer needed. 

https://github.com/lightvector/KataGo/releases

**Closed by lightvector** 2020-11-09 15:16 UTC

**Comment by apetresc** [comment] 2020-11-09 15:25
@lightvector Your comment and the patch notes indicate that libboost is no longer _required_, but is it still helpful in any way? Are there some conditional blocks that would use it if it were present, or is the dependency just completely removed?

**Comment by lightvector** [comment] 2020-11-09 15:32
It's completely gone. The only thing that it was used for was for the filesystem API, and @isty2e contributed a recent change to use a different header-only library instead.

We won't even need that one either if we can get to C++17, which has std::filesystem. But unfortunately keeping support for CUDA 10.2 means that we can't move to C++17, since nvcc is incompatible. (And unfortunately, CUDA 10.2 for a small set of users on certain GPUs who care about optimizing performance, might actually be the best performance, with CUDA 11 being worse, not better).
