### ISSUE TITLE
Please improve compatibility with Sabaki

### ISSUE THREAD

**Issue by ivysrono** [lightvector/KataGo#30] opened 2019-06-23 02:45 UTC
Could not use Sabaki's analysis, it only analysis the first step.
https://github.com/SabakiHQ/Sabaki/issues/587

Must set time_settings to enable, otherwise, show 'GTP ready, beginning main protocol loop' all the time.
But I do not want to set time limit.
https://github.com/SabakiHQ/Sabaki/issues/588

**Comment by lightvector** [comment] 2019-06-23 04:20
Have you tried the most recent version? Just two days after the recent 1.1 release, a bugfix was pushed that fixed some behavior with Sabaki and other Go tools. If after trying it you are still running into problems, please let me know what OS and settings you are using, how you compiled it, and the *exact* steps that you find will reproduce the issue. Thanks!

**Comment by ivysrono** [comment] 2019-06-23 05:08
I'm using windows by alreadydone's main.exe 
https://github.com/leela-zero/leela-zero/issues/2431#issuecomment-503423290

**Comment by lightvector** [comment] 2019-06-23 05:35
Right, but are you using the version that alreadydone compiled just after the release, when the bugs were still present in that compiled version? Or did you try to download it again more recently, when the bugs were fixed?

Please confirm that you are still encountering issues with a fresh download. If so, then can you explain what error you're getting? I don't understand what "Must set time_settings to enable" means, or what error you're getting after "analysis the first step". Is there an error message? Does the program crash? Does it just hang? What happens if you run main.exe *without* using Sabaki, instead you just directly run it and you take Sabaki's GTP commands and type them manually yourself into it?

**Comment by ivysrono** [comment] 2019-06-23 05:53
The main.exe which I'm using is equal to the attachment right now, I confirm.
I'm using KataGo by LizGoban great:
```
    {
      "label": "KataGo",
      "accelerator": "Ctrl + 0",
      "leelaz_command": "D:\\AI\\KataGo\\main.exe",
      "leelaz_args": ["gtp", "-model", "D:\\AI\\KataGo\\g104-b20c256.txt", "-config", "D:\\AI\\KataGo\\gtp.cfg"]
    },
    
```
1. time_settings
Without `time_settings`, Sabaki will do or log nothing more:
![图片](https://user-images.githubusercontent.com/2649544/59972192-4d50a880-95bd-11e9-8b86-309b04b8ddb6.png)
We have to set like:
![图片](https://user-images.githubusercontent.com/2649544/59972197-68231d00-95bd-11e9-802b-aa9b98b76f79.png)
It will work now:
![图片](https://user-images.githubusercontent.com/2649544/59972204-86891880-95bd-11e9-971a-8cf3e69ff970.png)

2. analysis
It's ok first:
![图片](https://user-images.githubusercontent.com/2649544/59972229-044d2400-95be-11e9-8fee-d731f8bcf09a.png)
However:
![图片](https://user-images.githubusercontent.com/2649544/59972237-2777d380-95be-11e9-8016-d7fabe70e1ca.png)
Stop and do nothing then.

So I have to use KataGo analysis by LizGoban.

**Comment by lightvector** [comment] 2019-06-23 06:53
Have you used Sabaki before successfully with other bots?

Are you sure it's stuck and doing nothing? What happens if you press F5 at the time it's doing nothing?

**Comment by ivysrono** [comment] 2019-06-23 07:45
My sabaki analysis by lz is OK.
![图片](https://user-images.githubusercontent.com/2649544/59973095-f357df00-95cc-11e9-893a-484084a109e6.png)
emm, F5 will focus KataGo play and it start analysis again. It's so different from other bots:
Others analysis both black and white, KataGo analysis the opponent only.

**Comment by lightvector** [comment] 2019-06-23 12:40
I still don't understand. 

There are multiple ways to begin a game and start a bot in Sabaki, and multiple slightly different sequences of keys you could be pressing or orders that you are doing things. I can't reproduce your problem on my end right now with the way I'm doing things, so maybe it is a problem with alreadydone's compiled version or Windows, or maybe it's a problem with the actual code logic itself, but I can't tell. So if you could **tell me the exact sequence of actions you do, at the level of detail of every individual button you press or every thing you type, starting from when you open Sabaki**, that would help.

Please do so for the case where you do NOT specify time_settings for either KataGo or LZ, and also when you're done, please attach here the KataGo gtp.log. Thanks.

**Comment by lightvector** [comment] 2019-06-23 13:00
Sorry, before you do that, I think I can guess what the problem is. You actually *are* using still the old buggy version, not the new version.

The comment you linked to in your earlier message was alreadydone's comment with the buggy version:
> I'm using windows by alreadydone's main.exe
> [leela-zero/leela-zero#2431 (comment)](https://github.com/leela-zero/leela-zero/issues/2431#issuecomment-503423290)

This version (the one you linked to) is buggy:
https://github.com/leela-zero/leela-zero/issues/2431#issuecomment-503423290
This version should be working:
https://github.com/leela-zero/leela-zero/issues/2431#issuecomment-503924636

Your linked comment is alreadydone's comment in that thread *before* the bug got fixed. But there is a different comment in that thread coming *after* the bug was fixed. So try the main.exe from the working comment. That's my best guess so far.

**Comment by kaorahi** [comment] 2019-06-23 13:44
> Others analysis both black and white, KataGo analysis the opponent only.

Do we need lz-genmove_analyze in addition to lz-analyze for "both side analysis" in Sabaki?

**Comment by ivysrono** [comment] 2019-06-23 13:48
Thank you very much.
The analysis is working as same as other bots.
However, could I show endstate in Sabaki just as LizGoban?

I need more time to test how to play game in Sabaki with KataGo.

**Comment by lightvector** [comment] 2019-06-23 13:55
@kaorahi - It seems ivysrono was actually using a buggy version after all, even though the bug was already fixed in a later version, and had not updated the version. The back and forth communication was sufficiently unclear that it took a long time to determine this. I think there is no problem now.

@ivysrono - you will need to talk to the author of Sabaki to have them implement visualization of the final ownership heatmap.

Closing, as I think this is resolved.

**Closed by lightvector** 2019-06-23 13:55 UTC
