### ISSUE TITLE
举报OmnipotentEntity在discord群任意踢人

### ISSUE THREAD

**Issue by awsjgy** [lightvector/KataGo#928] opened 2024-04-18 02:35 UTC
![(0 IXQJ{UXG} QA11%FOO4L](https://github.com/lightvector/KataGo/assets/59596750/6944fe4d-83e2-4001-a683-bf94803fbd3d)
I registered an account today and was kicked out after posting a message in the discord group. Please comment
![(0 IXQJ{UXG} QA11%FOO4L](https://github.com/lightvector/KataGo/assets/59596750/e92e2f71-77f6-451c-b778-4c6345a3beb9)

**Comment by awsjgy** [comment] 2024-04-18 02:46
我很气愤，OmnipotentEntity针对某种行为采取极端的封号行为，而不是针对行为。首先katago作者light说了在一个群发信息，不要多个群，我就换到help群发信息，OmnipotentEntity一刀切并没有和katago作者沟通好，就肆意妄为的踢人。首先另一个号注册发了一条信息，怎么就得罪人了。淘宝那么大的普通，封了号都可以注册另一个号进去。踢人是为了告诉别人不该怎么做，但是我被踢，都不知道原因在哪。

**Comment by awsjgy** [comment] 2024-04-18 02:49
管理员不是只有OmnipotentEntity他一个，一刀切的方式很1省力，但是与你的责任相违背，管理员是干嘛。你有本事昨天注册小号的时候我就问了一条信息，你就把我禁言了，有本事别删啊，中国昨天晚上六七点的时候，问了作者一个问题，如果修改棋盘的话，在哪个python文件中修改，你二话不说把我踢了，问题也删了，你为什么删问题呢？因为你知道理亏，发一个问题又是违反了什么行为呢？

**Comment by awsjgy** [comment] 2024-04-18 02:56
你知道一刀切是什么意思吗？就是图省事，直接踢了，简单了事

**Comment by awsjgy** [comment] 2024-04-18 02:57
你这个管理员当的很称职，针对某个人而不是某个行为。淘宝那么大的普通，他也只是封号，换了号注册可以继续上，管理员就你一个啊

**Comment by OmnipotentEntity** [comment] 2024-04-18 02:58
The following was intended to be DMed to you, and drafted by lightvector prior to my banning you from the discord. Because you opened this communication channel, I am sending it to you.

> I attempted to PM him but it doesn't appear that I can do so any more due to his settings, so I'll just stick here what I had drafted in case it's useful in the future.

-------------------------------------------------

> If you're willing, I'd like to offer a friendly suggestion that might be easier to understand about why other people may be frustrated with your questions:
It may be that they seem to suggest a lack of personal effort. Even if it was not your intention, it sounds sometimes like you are expecting people to do work to provide you answers where you are not doing work yourself.

> Here is an example. You asked a question much earlier and your entire message was the following and a screenshot:
>> Error installing katago sl

> A better method here would be to try to understand the error and solve it yourself first, and *demonstrate your effort* in the way you ask your question. For example, you could attempt to explain the error using your own words, showing that you are trying to understand it, such as:
>> Error installing katago sl. The message says there is an error from "import wx" on line 1, and it says "ModuleNotFoundError: No module named `wx`". I think this means it can't find the "wx" module.

> And then you would further demonstrate that you've already tried your best to solve the problem:
>> I tried googling/searching online for "ModuleNotFoundError: No module named `wx`" and I found answer A,B to this question, but I don't understand the answers because of reason C. Even if I ran D, I still got another error E.

> And so on. In this case, if you really did search online for the error before asking the question, you would surely have found multiple webpages online indicating to you that you needed to install wxPython, which was the same answer that someone told you and actually you would have solved it. And then you would not need to ask the question at all!

> If you do this for every problem you come across - use more personal effort to solve it yourself, and only ask if you can't solve it after many tries, and demonstrate your effort in your question, you will probably get a much more welcoming response in software-developer-oriented communities. 

> People in this kind of community culture also really appreciate someone who will put in effort contribute to the community! For example, if you learned how to do some especially and tricky that other people may not know, you could post a tutorial up in an appropriate channel to help other people do the same thing. Or you could share your own analysis of game positions and why a mistake is happening, instead of only posting questions about it. You could run test matches of 1000 games each comparing the strength of different bots so that other people can learn from the results, instead of just asking which one is stronger. People in such communities tend be more friendly if you are someone who is willing to also do the work and to contribute interesting things and help other people, equally as much as you are being helped yourself.

**Comment by awsjgy** [comment] 2024-04-18 03:00
你第一次封我号，我没意见，你确实提醒过我。但是第二次你封我就算了，昨天第三次封我是什么意思？作为管理员，能否有一点大局观。何况我昨天手机上新注册的一个号，看见katgao作者发的信息，就紧接着问，你就想当然把我封了，认为我是逃避禁言，你不觉得你太鲁莽了吗？你也知道，我不可能那么快注册第二个号，只是昨天正好看到了

**Comment by awsjgy** [comment] 2024-04-18 03:01
我以后不会再触犯多个频道发信息的规定了，但是我注册号后，你不要再封我了好吗？你为了我一个人，牺牲这么多，意义何在，我只是想了解kaatgo的一些最新信息，对我有什么好处

**Comment by awsjgy** [comment] 2024-04-18 03:02
你踢我的目的是我故意违反规定即使，但是我下次注册后再进来，不会和以前一样乱发了就行了啊，干嘛非得赶尽杀绝，如果只是针对某个行为，而不是个人的话

**Comment by awsjgy** [comment] 2024-04-18 03:03
你这样让我认为你是为了整我，而不是防止某个行为，我又不傻，你踢我一个按钮就可以解决。我下次不敢了啊

**Comment by awsjgy** [comment] 2024-04-18 03:05
你也知道我要进discord很容易，随便注册一个号就可以进来，尤其是谷歌qq号，我谷歌号都十几个。双方各退一步不行吗，

**Comment by awsjgy** [comment] 2024-04-18 03:11
> The following was intended to be DMed to you, and drafted by lightvector prior to my banning you from the discord. Because you opened this communication channel, I am sending it to you.
> 
> > I attempted to PM him but it doesn't appear that I can do so any more due to his settings, so I'll just stick here what I had drafted in case it's useful in the future.
> 
> > If you're willing, I'd like to offer a friendly suggestion that might be easier to understand about why other people may be frustrated with your questions:
> > It may be that they seem to suggest a lack of personal effort. Even if it was not your intention, it sounds sometimes like you are expecting people to do work to provide you answers where you are not doing work yourself.
> 
> > Here is an example. You asked a question much earlier and your entire message was the following and a screenshot:
> > > Error installing katago sl
> 
> > A better method here would be to try to understand the error and solve it yourself first, and _demonstrate your effort_ in the way you ask your question. For example, you could attempt to explain the error using your own words, showing that you are trying to understand it, such as:
> > > Error installing katago sl. The message says there is an error from "import wx" on line 1, and it says "ModuleNotFoundError: No module named `wx`". I think this means it can't find the "wx" module.
> 
> > And then you would further demonstrate that you've already tried your best to solve the problem:
> > > I tried googling/searching online for "ModuleNotFoundError: No module named `wx`" and I found answer A,B to this question, but I don't understand the answers because of reason C. Even if I ran D, I still got another error E.
> 
> > And so on. In this case, if you really did search online for the error before asking the question, you would surely have found multiple webpages online indicating to you that you needed to install wxPython, which was the same answer that someone told you and actually you would have solved it. And then you would not need to ask the question at all!
> 
> > If you do this for every problem you come across - use more personal effort to solve it yourself, and only ask if you can't solve it after many tries, and demonstrate your effort in your question, you will probably get a much more welcoming response in software-developer-oriented communities.
> 
> > People in this kind of community culture also really appreciate someone who will put in effort contribute to the community! For example, if you learned how to do some especially and tricky that other people may not know, you could post a tutorial up in an appropriate channel to help other people do the same thing. Or you could share your own analysis of game positions and why a mistake is happening, instead of only posting questions about it. You could run test matches of 1000 games each comparing the strength of different bots so that other people can learn from the results, instead of just asking which one is stronger. People in such communities tend be more friendly if you are someone who is willing to also do the work and to contribute interesting things and help other people, equally as much as you are being helped yourself.

作者发的比你的成熟多了，听上去舒服多了，这样说我可以接受。我知道作者是深明大义之人

**Comment by FengmingGo** [comment] 2024-04-18 15:17
Do you have to do this? First of all, it's not right to speak Chinese here.

**Comment by FengmingGo** [comment] 2024-04-18 15:20
Do you think you're doing the right thing? He removed you from the forum because you kept asking weird questions on the forum.

**Comment by lightvector** [comment] 2024-04-18 15:48
@awsjgy - I empathize with you. It's also important to respect the rules and wishes of the owner of a server and not to try to unilaterally ignore or evade them, and to take responsibility for your own actions and choices. Please take some time to calm down - go have fun and do something else for a while. Go has been around for thousands of years and will still be here later.

Closing this thread.

**Closed by lightvector** 2024-04-18 15:48 UTC

**Comment by awsjgy** [comment] 2024-04-18 23:57
He misunderstood what I meant. I didn't try to escape. My phone was registered with another account. When he kicked me, I was sending messages with another account. His abuse of power and subjective judgment are disgusting and upsetting. He should focus on behavior, not individuals. Just because he has a good relationship with you, doesn't mean that what he does is right. What's more, I registered another account and just said one sentence and blocked me. If judges are like him and subjectively determine others are guilty without any evidence on the table, I don't know how many people will be wronged.&nbsp;


2189651660
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Ya ***@***.***&gt;; 
发送时间: 2024年4月18日(星期四) 晚上11:48
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [lightvector/KataGo] 举报OmnipotentEntity在discord群任意踢人 (Issue #928)














 
@awsjgy - I empathize with you. It's also important to respect the rules and wishes of the owner of a server and not to try to unilaterally ignore or evade them, and to take responsibility for your own actions and choices. Please take some time to calm down - go have fun and do something else for a while. Go has been around for thousands of years and will still be here later.
 
Closing this thread.

**Comment by awsjgy** [comment] 2024-04-19 00:45
***@***.***/1230670082934440017/1230670097303998534



adsfds32

adsfds32
在线


































私信



lightvector









搜索




















聊天



lightvector

lightvector
这是您与&nbsp;lightvector&nbsp;私信记录的开头。
1 个共同服务器


已发送好友请求
屏蔽



2024年4月19日


adsfds32 — 今天08:03
The omnipotent misunderstood what I meant. It is wrong to kick people randomly without clear evidence. It cannot be because he subjectively thinks that I am deliberately evading the ban, not to mention that I did not speak freely after registering another account. You can't favor him just because you have a good relationship with her. It would be great if the judges judged the crime like he did. What makes me most angry is that yesterday on the Chinese channel, I just answered one sentence and he thought it was me. If you kicked me, whether it was for the person or for the behavior, you have to weigh it yourself. I explained to her that I didn't mean to avoid being banned, but he didn't believe me. This one-size-fits-all, easy-to-kick method is easy for him, but it is very costly for the person being kicked. You know it’s not easy to register an account. On a platform as big as Taobao, even if you are banned, it is because you have violated the regulations, and if you run your registr










[08:05]This is another account I registered yesterday. I don’t dare to send messages now. Later he thought it was me and kicked me out. What do you think I should do? After he banned me, I registered another account called fbnbcdgb. I posted this sentence on my Chinese channel. He thought it was me and kicked me out. Do you think this is reasonable?





















[08:07]And he kicked me. I didn’t know what my mistake was. I will make the same mistake next time. Shouldn't kicking someone be a deliberate violation of regulations? Since you reminded me to only send messages in the help channel, I have been sending messages in the help channel. As for you saying that you reminded me when I sent messages on katago channel





adsfds32 — 今天08:35
People prefer to believe what is easy to see, and few are willing to spend cognitive resources to investigate the true nature behind things. I'm not that stupid. People who think like this are particularly selfish in order to avoid banning their registration number. Registering an account is much more difficult than banning one. If I register an account, he can ban me at will. I am not that stupid. I am the weak one, and he is the one with the power. Maybe people see it and it’s easier to believe that I’m evading the ban. I said that I registered another account on my mobile phone at that time, and then I saw the message you replied to, the author, and asked again. I didn't know he had banned my other account




[08:38]I don’t dare to speak now anyway, because his account was blocked because I registered it, not because I violated some rules. Can't I change my chances again?





















[08:39]It would be too hasty if judges judge the facts of the case in this way. I don’t know how many people will be wronged. Even if you wrong one person, it is a serious mistake. You cannot decide whether to ban someone based on your thinking. There needs to be evidence. Even if I register an account, if I don't speak casually anymore, that's fine. There's no need to kill them all like this. What's more, this is the Internet era, and you don't know if the account is registered by the same user. Do you think what I said makes sense? If my account is blocked again, it must be because omnipotententiyu thought it was my account and blocked my account for this reason. In order to avoid being blocked, I keep the evidence here.
















***@***.***
﻿


























进行选择
















lightvector
lightvector












2189651660
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "2189651660"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月19日(星期五) 上午7:57
***@***.******@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;回复： [lightvector/KataGo] 举报OmnipotentEntity在discord群任意踢人 (Issue #928)



 &nbsp;


2189651660
***@***.***



&nbsp;




------------------ 原始邮件 ------------------
发件人: "Ya ***@***.***&gt;; 
发送时间: 2024年4月18日(星期四) 晚上11:48
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [lightvector/KataGo] 举报OmnipotentEntity在discord群任意踢人 (Issue #928)














 
@awsjgy - I empathize with you. It's also important to respect the rules and wishes of the owner of a server and not to try to unilaterally ignore or evade them, and to take responsibility for your own actions and choices. Please take some time to calm down - go have fun and do something else for a while. Go has been around for thousands of years and will still be here later.
 
Closing this thread.

**Comment by awsjgy** [comment] 2024-04-19 06:14
There is no denying that he removed me, but what's the deal with him removing me again after I register my number and come in? Is that a personal attack?You don't seem to understand the situation very well and only know the shallow reasons, if I asked strange questions he could have told me, there is no need to ban me for posting in multiple groups, isn't that a bit much&nbsp;


2189651660
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Ya ***@***.***&gt;; 
发送时间: 2024年4月18日(星期四) 晚上11:21
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [lightvector/KataGo] 举报OmnipotentEntity在discord群任意踢人 (Issue #928)














 
Do you think you're doing the right thing? He removed you from the forum because you kept asking weird questions on the forum.

**Comment by awsjgy** [comment] 2024-04-19 06:20
I re-registered as "fbnbcdgb" and sent this message "Updated to 655 yesterday, you're talking about the last version". I don't think I did the right thing, but as an administrator, is it acceptable for him to handle this? Even if I did wrong, isn't there something wrong with the way he handled the issue?
&nbsp;


2189651660
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Ya ***@***.***&gt;; 
发送时间: 2024年4月18日(星期四) 晚上11:17
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [lightvector/KataGo] 举报OmnipotentEntity在discord群任意踢人 (Issue #928)














 
Do you have to do this? First of all, it's not right to speak Chinese here.

**Comment by awsjgy** [comment] 2024-04-19 06:27
If you had said earlier that I kept asking weird questions, I probably wouldn't have been banned, and instead of making that clear, you said that it was different groups that kept sending messages, so then after getting kicked like that, I still don't know why. Isn't this a management problem?
Isn't it normal to make mistakes, but how do you want me to think when you don't make your questions clear?Why do I always get the feeling that you're favoring him, since you and he are both admins and then communicate more on Go, I admit I have a problem, but it seems like you're completely oblivious to the opomnent problem. Kicked me off and I didn't say this number to come back in, but to come in another way by registering a smaller number, don't go overboard with it
2189651660
***@***.***

2189651660
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "2189651660"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月19日(星期五) 下午2:14
***@***.******@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;回复： [lightvector/KataGo] 举报OmnipotentEntity在discord群任意踢人 (Issue #928)



 &nbsp;


2189651660
***@***.***



&nbsp;




------------------ 原始邮件 ------------------
发件人: "Ya ***@***.***&gt;; 
发送时间: 2024年4月18日(星期四) 晚上11:21
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [lightvector/KataGo] 举报OmnipotentEntity在discord群任意踢人 (Issue #928)














 
Do you think you're doing the right thing? He removed you from the forum because you kept asking weird questions on the forum.

**Comment by awsjgy** [comment] 2024-04-19 07:13
I'm not dissatisfied with his behavior of deleting me, but his behavior against me is not satisfied, I re-registered a number, why did he find nothing to delete me, I did not ask questions ah, he is not the abuse of power to engage in the habit of a number of me to keep asking you, the back of the number did not operate like this ah


2189651660
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "2189651660"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月19日(星期五) 下午2:27
***@***.******@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;回复： [lightvector/KataGo] 举报OmnipotentEntity在discord群任意踢人 (Issue #928)



 
If you had said earlier that I kept asking weird questions, I probably wouldn't have been banned, and instead of making that clear, you said that it was different groups that kept sending messages, so then after getting kicked like that, I still don't know why. Isn't this a management problem?
Isn't it normal to make mistakes, but how do you want me to think when you don't make your questions clear?Why do I always get the feeling that you're favoring him, since you and he are both admins and then communicate more on Go, I admit I have a problem, but it seems like you're completely oblivious to the opomnent problem. Kicked me off and I didn't say this number to come back in, but to come in another way by registering a smaller number, don't go overboard with it
2189651660
***@***.***

2189651660
***@***.***



&nbsp;




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "2189651660"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月19日(星期五) 下午2:14
***@***.******@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;回复： [lightvector/KataGo] 举报OmnipotentEntity在discord群任意踢人 (Issue #928)



 There is no denying that he removed me, but what's the deal with him removing me again after I register my number and come in? Is that a personal attack?You don't seem to understand the situation very well and only know the shallow reasons, if I asked strange questions he could have told me, there is no need to ban me for posting in multiple groups, isn't that a bit much&nbsp;


2189651660
***@***.***



&nbsp;




------------------ 原始邮件 ------------------
发件人: "Ya ***@***.***&gt;; 
发送时间: 2024年4月18日(星期四) 晚上11:21
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [lightvector/KataGo] 举报OmnipotentEntity在discord群任意踢人 (Issue #928)














 
Do you think you're doing the right thing? He removed you from the forum because you kept asking weird questions on the forum.
