### ISSUE TITLE
Can Katago disclose the training data?

### ISSUE THREAD

**Issue by katajigo** [lightvector/KataGo#463] opened 2021-04-12 14:42 UTC
Can Katago disclose the training data？And give a link.I want to use the training data of the katago to make alchemy, okay?

**Comment by lightvector** [comment] 2021-04-12 21:22
This is essentially a duplicate of https://github.com/lightvector/KataGo/issues/460

Please ask there if you have any questions - the short answer is that it may be a while, unless you yourself can help out, or recruit some people to help out. :)

**Closed by lightvector** 2021-04-12 21:22 UTC
